/**
 * Generated by `scripts/measure-expression.mjs` — do not edit.
 *
 * Per GM program: the low-pass corner at each probed velocity, the measured
 * release, and whether the instrument holds its level while held.
 * See `rn/playback/expression.ts` for what applies it.
 */
/**
 * SHA-256 of the soundfont these numbers were measured from.
 *
 * Swap the font and every cutoff, release and sustain flag here describes an
 * instrument that is no longer being played — silently, because nothing about a
 * stale table throws. music_app owns the font, so music_app asserts the match.
 */
export const MEASURED_FROM_SHA256 = '2aacd036d7058d40a371846ef2f5dc5f130d648ab3837fe2626591ba49a71254';

export type ExpressionEntry = {
  cutoffs: Record<string, number>;
  releaseSec: number | null;
  sustains: boolean;
};

export const EXPRESSION_TABLE: Record<string, ExpressionEntry> = {
 "0": {
  "cutoffs": {
   "16": 556,
   "32": 1111,
   "64": 2222,
   "96": 4989
  },
  "releaseSec": 0.52,
  "sustains": false
 },
 "1": {
  "cutoffs": {
   "16": 700,
   "32": 990,
   "64": 2222,
   "96": 2222
  },
  "releaseSec": 0.45,
  "sustains": false
 },
 "2": {
  "cutoffs": {
   "16": 5600,
   "32": 5600,
   "64": 5600
  },
  "releaseSec": 0.54,
  "sustains": false
 },
 "3": {
  "cutoffs": {
   "16": 1111,
   "32": 1980,
   "64": 4989,
   "96": 7056
  },
  "releaseSec": 0.48,
  "sustains": false
 },
 "4": {
  "cutoffs": {
   "16": 1764,
   "32": 2222
  },
  "releaseSec": 0.4,
  "sustains": true
 },
 "5": {
  "cutoffs": {
   "16": 495,
   "32": 495,
   "64": 700,
   "96": 1111
  },
  "releaseSec": 0.41,
  "sustains": true
 },
 "6": {
  "cutoffs": {},
  "releaseSec": 0.71,
  "sustains": false
 },
 "7": {
  "cutoffs": {},
  "releaseSec": 0.59,
  "sustains": true
 },
 "8": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "9": {
  "cutoffs": {
   "16": 11200,
   "32": 11200,
   "64": 4989,
   "96": 14111
  },
  "releaseSec": null,
  "sustains": false
 },
 "10": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "11": {
  "cutoffs": {
   "16": 786,
   "32": 786,
   "64": 786,
   "96": 3528
  },
  "releaseSec": 0.43,
  "sustains": false
 },
 "12": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "13": {
  "cutoffs": {
   "16": 2495,
   "32": 2495,
   "64": 2495
  },
  "releaseSec": null,
  "sustains": false
 },
 "14": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "15": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "16": {
  "cutoffs": {},
  "releaseSec": 0.72,
  "sustains": true
 },
 "17": {
  "cutoffs": {},
  "releaseSec": 0.54,
  "sustains": true
 },
 "18": {
  "cutoffs": {},
  "releaseSec": 0.42,
  "sustains": true
 },
 "19": {
  "cutoffs": {},
  "releaseSec": 1.26,
  "sustains": true
 },
 "20": {
  "cutoffs": {},
  "releaseSec": 0.48,
  "sustains": true
 },
 "21": {
  "cutoffs": {},
  "releaseSec": 0.52,
  "sustains": true
 },
 "22": {
  "cutoffs": {},
  "releaseSec": 0.41,
  "sustains": true
 },
 "23": {
  "cutoffs": {},
  "releaseSec": 0.16,
  "sustains": true
 },
 "24": {
  "cutoffs": {
   "16": 2495,
   "32": 2495,
   "64": 2222,
   "96": 7920
  },
  "releaseSec": 0.72,
  "sustains": false
 },
 "25": {
  "cutoffs": {
   "16": 2800,
   "32": 3960,
   "64": 7056,
   "96": 12572
  },
  "releaseSec": 0.55,
  "sustains": false
 },
 "26": {
  "cutoffs": {
   "16": 786,
   "32": 882,
   "64": 882,
   "96": 4445
  },
  "releaseSec": 0.28,
  "sustains": false
 },
 "27": {
  "cutoffs": {},
  "releaseSec": 0.49,
  "sustains": false
 },
 "28": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "29": {
  "cutoffs": {},
  "releaseSec": 0.54,
  "sustains": true
 },
 "30": {
  "cutoffs": {},
  "releaseSec": 0.65,
  "sustains": true
 },
 "31": {
  "cutoffs": {},
  "releaseSec": 0.26,
  "sustains": true
 },
 "32": {
  "cutoffs": {
   "16": 1111,
   "32": 1400,
   "64": 3143,
   "96": 6286
  },
  "releaseSec": 0.38,
  "sustains": false
 },
 "33": {
  "cutoffs": {
   "16": 1980,
   "32": 2800
  },
  "releaseSec": 0.19,
  "sustains": true
 },
 "34": {
  "cutoffs": {},
  "releaseSec": 0.3,
  "sustains": true
 },
 "35": {
  "cutoffs": {
   "64": 12572
  },
  "releaseSec": 0.13,
  "sustains": true
 },
 "36": {
  "cutoffs": {
   "16": 2800,
   "32": 3528,
   "64": 8889
  },
  "releaseSec": 0.12,
  "sustains": true
 },
 "37": {
  "cutoffs": {},
  "releaseSec": 0.29,
  "sustains": true
 },
 "38": {
  "cutoffs": {
   "16": 495,
   "32": 495,
   "64": 786
  },
  "releaseSec": 0.25,
  "sustains": true
 },
 "39": {
  "cutoffs": {
   "16": 495,
   "32": 786,
   "64": 2222,
   "96": 7920
  },
  "releaseSec": null,
  "sustains": false
 },
 "40": {
  "cutoffs": {},
  "releaseSec": 0.59,
  "sustains": true
 },
 "41": {
  "cutoffs": {},
  "releaseSec": 0.64,
  "sustains": true
 },
 "42": {
  "cutoffs": {},
  "releaseSec": 0.64,
  "sustains": true
 },
 "43": {
  "cutoffs": {},
  "releaseSec": 0.61,
  "sustains": true
 },
 "44": {
  "cutoffs": {},
  "releaseSec": 0.57,
  "sustains": true
 },
 "45": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "46": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "47": {
  "cutoffs": {
   "16": 1111,
   "32": 1111,
   "64": 1111,
   "96": 3528
  },
  "releaseSec": null,
  "sustains": false
 },
 "48": {
  "cutoffs": {
   "16": 7056,
   "32": 8889,
   "64": 12572,
   "96": 17779
  },
  "releaseSec": 0.57,
  "sustains": true
 },
 "49": {
  "cutoffs": {
   "16": 7056,
   "32": 8889,
   "64": 12572,
   "96": 17779
  },
  "releaseSec": 0.59,
  "sustains": true
 },
 "50": {
  "cutoffs": {
   "16": 700,
   "32": 990,
   "64": 1764,
   "96": 2800
  },
  "releaseSec": null,
  "sustains": true
 },
 "51": {
  "cutoffs": {
   "16": 1400,
   "32": 1980,
   "64": 2800,
   "96": 4445
  },
  "releaseSec": null,
  "sustains": true
 },
 "52": {
  "cutoffs": {},
  "releaseSec": 0.72,
  "sustains": true
 },
 "53": {
  "cutoffs": {},
  "releaseSec": 0.62,
  "sustains": true
 },
 "54": {
  "cutoffs": {},
  "releaseSec": 0.75,
  "sustains": true
 },
 "55": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "56": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222,
   "96": 7056
  },
  "releaseSec": 0.72,
  "sustains": true
 },
 "57": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222,
   "96": 7056
  },
  "releaseSec": 0.72,
  "sustains": true
 },
 "58": {
  "cutoffs": {},
  "releaseSec": 0.42,
  "sustains": true
 },
 "59": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222,
   "96": 7920
  },
  "releaseSec": 0.64,
  "sustains": true
 },
 "60": {
  "cutoffs": {
   "16": 1400,
   "32": 1400,
   "64": 1400,
   "96": 6286
  },
  "releaseSec": 0.61,
  "sustains": true
 },
 "61": {
  "cutoffs": {
   "16": 1980,
   "32": 3143,
   "64": 6286,
   "96": 12572
  },
  "releaseSec": 0.84,
  "sustains": true
 },
 "62": {
  "cutoffs": {
   "16": 1571,
   "32": 1764,
   "64": 2222,
   "96": 3143
  },
  "releaseSec": 0.47,
  "sustains": true
 },
 "63": {
  "cutoffs": {
   "16": 1764,
   "32": 1980,
   "64": 3143,
   "96": 4989
  },
  "releaseSec": 0.89,
  "sustains": true
 },
 "64": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222,
   "96": 7920
  },
  "releaseSec": 0.56,
  "sustains": true
 },
 "65": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222,
   "96": 7920
  },
  "releaseSec": 0.58,
  "sustains": true
 },
 "66": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222,
   "96": 7056
  },
  "releaseSec": 0.58,
  "sustains": true
 },
 "67": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222,
   "96": 7920
  },
  "releaseSec": 0.41,
  "sustains": true
 },
 "68": {
  "cutoffs": {},
  "releaseSec": 0.73,
  "sustains": true
 },
 "69": {
  "cutoffs": {},
  "releaseSec": 0.61,
  "sustains": true
 },
 "70": {
  "cutoffs": {},
  "releaseSec": 0.62,
  "sustains": true
 },
 "71": {
  "cutoffs": {
   "16": 882,
   "32": 1400,
   "64": 3960,
   "96": 9978
  },
  "releaseSec": 0.74,
  "sustains": true
 },
 "72": {
  "cutoffs": {},
  "releaseSec": 0.42,
  "sustains": true
 },
 "73": {
  "cutoffs": {},
  "releaseSec": 0.8,
  "sustains": true
 },
 "74": {
  "cutoffs": {
   "32": 4445,
   "64": 4445,
   "96": 15839
  },
  "releaseSec": 0.42,
  "sustains": true
 },
 "75": {
  "cutoffs": {
   "16": 1980,
   "32": 1980,
   "64": 1980,
   "96": 6286
  },
  "releaseSec": 0.41,
  "sustains": true
 },
 "76": {
  "cutoffs": {},
  "releaseSec": 0.23,
  "sustains": false
 },
 "77": {
  "cutoffs": {},
  "releaseSec": 0.4,
  "sustains": true
 },
 "78": {
  "cutoffs": {},
  "releaseSec": 0.4,
  "sustains": false
 },
 "79": {
  "cutoffs": {
   "16": 2495,
   "32": 3528,
   "64": 7056,
   "96": 14111
  },
  "releaseSec": 0.41,
  "sustains": true
 },
 "80": {
  "cutoffs": {
   "16": 2222,
   "32": 2495,
   "64": 3528,
   "96": 4445
  },
  "releaseSec": 0.13,
  "sustains": true
 },
 "81": {
  "cutoffs": {
   "16": 3960,
   "32": 3960,
   "64": 4445,
   "96": 5600
  },
  "releaseSec": 0.09,
  "sustains": true
 },
 "82": {
  "cutoffs": {
   "16": 441,
   "32": 495,
   "64": 495,
   "96": 4989
  },
  "releaseSec": null,
  "sustains": true
 },
 "83": {
  "cutoffs": {
   "16": 1111,
   "32": 1764,
   "64": 2495,
   "96": 786
  },
  "releaseSec": 0.43,
  "sustains": true
 },
 "84": {
  "cutoffs": {},
  "releaseSec": 0.4,
  "sustains": false
 },
 "85": {
  "cutoffs": {},
  "releaseSec": 0.57,
  "sustains": true
 },
 "86": {
  "cutoffs": {
   "16": 1980,
   "32": 2222,
   "64": 2800
  },
  "releaseSec": 0.44,
  "sustains": true
 },
 "87": {
  "cutoffs": {
   "16": 1571,
   "32": 1764,
   "64": 2495,
   "96": 3528
  },
  "releaseSec": 0.07,
  "sustains": true
 },
 "88": {
  "cutoffs": {
   "16": 441,
   "32": 495,
   "64": 700,
   "96": 1111
  },
  "releaseSec": null,
  "sustains": false
 },
 "89": {
  "cutoffs": {
   "16": 441,
   "32": 495,
   "64": 556,
   "96": 786
  },
  "releaseSec": null,
  "sustains": true
 },
 "90": {
  "cutoffs": {
   "16": 990,
   "32": 1400,
   "64": 2495,
   "96": 4445
  },
  "releaseSec": 0.12,
  "sustains": true
 },
 "91": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": true
 },
 "92": {
  "cutoffs": {
   "16": 495,
   "32": 495,
   "64": 441,
   "96": 495
  },
  "releaseSec": null,
  "sustains": false
 },
 "93": {
  "cutoffs": {
   "16": 990,
   "32": 1400,
   "64": 1980,
   "96": 2495
  },
  "releaseSec": null,
  "sustains": true
 },
 "94": {
  "cutoffs": {
   "16": 700,
   "32": 624,
   "64": 990,
   "96": 1764
  },
  "releaseSec": 1.37,
  "sustains": true
 },
 "95": {
  "cutoffs": {
   "16": 556,
   "32": 556,
   "64": 1111,
   "96": 1764
  },
  "releaseSec": null,
  "sustains": true
 },
 "96": {
  "cutoffs": {
   "16": 2222,
   "32": 2222,
   "64": 2222
  },
  "releaseSec": 1.17,
  "sustains": true
 },
 "97": {
  "cutoffs": {},
  "releaseSec": 0.97,
  "sustains": true
 },
 "98": {
  "cutoffs": {
   "16": 4989,
   "32": 4989,
   "64": 9978,
   "96": 15839
  },
  "releaseSec": null,
  "sustains": false
 },
 "99": {
  "cutoffs": {
   "16": 441,
   "32": 441,
   "64": 441,
   "96": 786
  },
  "releaseSec": 1.42,
  "sustains": false
 },
 "100": {
  "cutoffs": {
   "16": 1400,
   "32": 1764,
   "64": 1764,
   "96": 1764
  },
  "releaseSec": 1.46,
  "sustains": false
 },
 "101": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": true
 },
 "102": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": true
 },
 "103": {
  "cutoffs": {
   "16": 441,
   "32": 624,
   "64": 990,
   "96": 1980
  },
  "releaseSec": 1.49,
  "sustains": true
 },
 "104": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "105": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "106": {
  "cutoffs": {},
  "releaseSec": 0.51,
  "sustains": false
 },
 "107": {
  "cutoffs": {},
  "releaseSec": 1.29,
  "sustains": false
 },
 "108": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "109": {
  "cutoffs": {},
  "releaseSec": 0.77,
  "sustains": true
 },
 "110": {
  "cutoffs": {},
  "releaseSec": 0.77,
  "sustains": true
 },
 "111": {
  "cutoffs": {},
  "releaseSec": 0.59,
  "sustains": true
 },
 "112": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "113": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "114": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "115": {
  "cutoffs": {
   "16": 624
  },
  "releaseSec": null,
  "sustains": false
 },
 "116": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "117": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "118": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "119": {
  "cutoffs": {},
  "releaseSec": 0.82,
  "sustains": true
 },
 "120": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "121": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "122": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": true
 },
 "123": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 },
 "124": {
  "cutoffs": {},
  "releaseSec": 0.6,
  "sustains": false
 },
 "125": {
  "cutoffs": {},
  "releaseSec": 1.25,
  "sustains": true
 },
 "126": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": true
 },
 "127": {
  "cutoffs": {},
  "releaseSec": null,
  "sustains": false
 }
};
